export const PAYMENT_OPTIONS = {
  bill: "bill",
  contra: "contra",
  passbook_update: "passbook_update",
  cashbook_update: "cashbook_update",
  opening_current_update: "opening_current_update",
  journal: "journal",
};

export const ENTRY_TYPE_OPTIONS = [
  { label: "Withdrawal", value: "withdrawal" },
  { label: "Deposite", value: "deposite" },
];

export const PARTICULAR_OPTIONS = [
  {
    label: "BROKERAGE AND CHECKING",
    value: "brokerage_and_checking",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "CASH SALARY PAID",
    value: "cash_salary_paid",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "CC/OD INTEREST",
    value: "cc_od_interest",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "CLAIM EXPENSE",
    value: "claim_expenses",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "ELECTRIC",
    value: "electric",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "GAS",
    value: "gas",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "INSURANCE AND TAXES",
    value: "insurance_and_taxes",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "INTEREST PAID",
    value: "interest_paid",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "INTEREST RECEIVED",
    value: "interest_received",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "LOAD INTEREST",
    value: "load_interest",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "MACHINERY EXPENSES",
    value: "machinery_expenses",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "MILLGINE AND OIL",
    value: "millgine_and_oil",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "MISCELLANEOUS",
    value: "miscellaneous",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "OFFICE EXPENSES",
    value: "office_expenses",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "OTHER INCOME",
    value: "other_income",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "PETROL AND PHONE",
    value: "petrol_and_phone",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },
  {
    label: "POWER BILL",
    value: "power_bill",
    is_cost_per_meter: true,
    color: "#B8860B",
    head: "ADMINISTRATIVE EXPENSE",
  },

  {
    label: "CGST",
    value: "cgst",
    is_cost_per_meter: false,
    color: "blue",
    head: "CGST",
  },
  {
    label: "CHARGES",
    value: "charges",
    is_cost_per_meter: false,
    color: "blue",
    head: "",
  },
  {
    label: "FALSE ENTRY",
    value: "false_entry",
    is_cost_per_meter: false,
    color: "blue",
    head: "",
  },
  {
    label: "IGST",
    value: "igst",
    is_cost_per_meter: false,
    color: "blue",
    head: "IGST",
  },
  {
    label: "PAYMENT",
    value: "payment",
    is_cost_per_meter: false,
    color: "blue",
    head: "",
  },
  {
    label: "SELF",
    value: "self",
    is_cost_per_meter: false,
    color: "blue",
    head: "CASH ON HAND",
  },
  {
    label: "SGST",
    value: "sgst",
    is_cost_per_meter: false,
    color: "blue",
    head: "SGST",
  },
  {
    label: "SUSPENSE ACCOUNT",
    value: "suspense_account",
    is_cost_per_meter: false,
    color: "blue",
    head: "",
  },
  {
    label: "TOTAL WAGES AND ADVANCES",
    value: "total_wages_and_advances",
    is_cost_per_meter: false,
    color: "blue",
    head: "ADMINISTRATIVE EXPENSE",
  },
];

export const HEAD_OPTIONS = [
  { label: "ADMINISTRATIVE EXPENSE", value: "ADMINISTRATIVE EXPENSE" },
  { label: "CAPITAL ACCOUNT", value: "CAPITAL ACCOUNT" },
  { label: "CASH ON HAND", value: "CASH ON HAND" },
  { label: "CGST", value: "CGST" },
  { label: "CURRENT ASSETS", value: "CURRENT ASSETS" },
  { label: "CURRENT LIABILITY", value: "CURRENT LIABILITY" },
  { label: "DEPOSIT", value: "DEPOSIT" },
  { label: "FIXED ASSETS", value: "FIXED ASSETS" },
  { label: "IGST", value: "IGST" },
  { label: "INVESTMENT", value: "INVESTMENT" },
  { label: "LOAN AND ADVANCES", value: "LOAN AND ADVANCES" },
  { label: "LOANS (LIABILITY)", value: "LOANS (LIABILITY)" },
  { label: "OTHER INCOME", value: "OTHER INCOME" },
  { label: "SGST", value: "SGST" },
  { label: "TCS", value: "TCS" },
  { label: "TDS PAY (Liability)", value: "TDS(Pay)" },
  { label: "TDS DEDUCT (ASSET) (Asset)", value: "TDS DEDUCT (ASSET)" },
];
