name: Build and Deploy

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner, if needed

    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd /root/staging_code/FtoF-FE
          git pull origin master
          source ~/.bashrc
          npm install
          pm2 reload staging
